config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users
  resources :sessions
  delete "/logout" =>  "sessions#destroy", as: :logout
  get 'about', to: 'welcome#about'
  get 'download', to: 'welcome#download_resume'

  resources :articles do
    get :search, on: :collection
    post :preview, on: :collection
    resources :comments
  end

  resources :resumes, only: [:edit, :update]

  # 用户相关信息路由跟在用户名之后
  #constraints(id: User::USERNAME_FORMAT) do
    #resources :users, path: '', as: 'users' do
      #member do
        #get :articles
        #get :comments
      #end
    #end

  #end

  # 设置
  resource :setting do
    member do
      get :profile
      get :reward
      get :password
    end
  end

  # 后台管理
  namespace :admin do
    root 'sessions#new'
    resources :sessions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  searchkick

  belongs_to :user
  belongs_to :category
  has_many :comments

end

app/models/article_tag_ship.rb
class ArticleTagShip < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article
end

app/models/personal_category.rb
class PersonalCategory < ApplicationRecord
end

app/models/resume.rb
class Resume < ApplicationRecord

  belongs_to :user

  def generate_pdf(content)
    Prawn::Document.generate("test.pdf") do
      file = "#{Prawn::DATADIR}/fonts/gkai00mp.ttf"
      font_families["Kai"] = {
        :normal => { :file => file, :font => "Kai" }
      }
      text content, :fallback_fonts => ["Times-Roman", "Kai"]
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  attr_accessor :password, :password_confirmation

  has_many :articles, dependent: :destroy
  has_many :comments
  has_one :resume

  USERNAME_FORMAT = /[a-zA-Z0-9\-\_]*/

  def username
    self.name.nil? ? self.email.split('@').first : self.name
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :auth_user, except: [:show]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all.page(params[:page] || 1).
      per_page(params[:per_page] || 10).order('id desc')
  end

  def show
    @article.view_count += 1
    @article.save!
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.view_count = 0
    @article.content_html = markdown(@article.content)
    if @article.save
      flash[:info] = "文章发布成功！"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update_attributes(article_params)
      flash[:success] = "update article successful"
      redirect_to @article
    else
      render 'deit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "删除成功"
      redirect_to articles_path
    else
      flash[:notice] = "删除失败"
      redirect_back fallback_location: articles_path
    end
  end

  def preview
    content = markdown(params[:content])
    render html: content
  end

  def search
    @articles = Article.search(params[:key], fields: [:title], page: params[:page], per_page: 10)

    render file: 'welcome/index'
  end

  private
  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :category_id, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  layout false
  before_action :auth_user
  before_action :find_article

  def index
    @comments = @article.comments
  end

  def create
    @comment = @article.comments.new
    @comment.content = params[:content]
    @comment.user_id = current_user.id
    @comment.content_html = markdown(@comment.content)
    @comment.comment_at = Time.now 

    if @comment.save
      @comments = @article.reload.comments
      render json: {
        status: 'ok',
        data: render_to_string(file: 'comments/index')
      }
    else
      render json: {
        status: 'error',
        data: render_to_string(file: 'comments/new')
      }
    end
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    @comments = @article.comments

    redirect_to article_path(@article)
  end


  private
  def find_article
    @article = Article.find(params[:article_id])
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def edit
    @resume = current_user.resume
  end

  def update
    @resume = current_user.resume
    @resume.attributes = params.require(:resume).permit(:title, :content)
    @resume.content_html = markdown(params[:resume][:content])
    if @resume.save
      redirect_to about_path
    else
      render action: :edit
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    if user = login(params[:email], params[:password])

      flash[:notice] = "登陆成功"
      redirect_to root_path
    else
      flash[:notice] = "邮箱或者密码不正确"
      redirect_to new_session_path
    end
  end

  def destroy
    logout
    flash[:notice] = "退出成功"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user)
      .permit(:email, :password, :password_confirmation))

    if @user.save
      Resume.create!(user_id: @user.id, title: "#{@user.username}的简历", content: "内容" )
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.all.page(params[:page] || 1).
      per_page(params[:per_page] || 10).order('id desc')
  end

  def about
    @resume = User.first.resume
  end

  def download_resume
    @resume = User.first.resume
    content = @resume.content_html.nil? ? @resume.content : @resume.content_html
    kit = PDFKit.new(content, page_size: 'Letter')
    pdf = kit.to_pdf
    file_name = "李亚中的个人简历.pdf"
    send_data(pdf, filename: file_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def avatar_tag(user, width = 96)
    if user.avatar?
      avatar_url = user.avatar.url
    else
      avatar_id = Digest::MD5::hexdigest(user.email.downcase)
      avatar_url = "https://secure.gravatar.com/avatar/#{avatar_id}"
    end
    image_tag(avatar_url, alt: user.username, class: "avatar-#{width}")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<div class="container-fluid">
  <div class="col-md-10 col-lg-10 col-center-block content-wrap">
    <%= simple_form_for @article, remote: false do |f| %>
      <div class="form-group">
        <div class="row">
          <div class="col-md-3">
            <%= f.input :category_id, label: false, class: "form-control", prompt: "请选择", collection: Category.all %>
          </div>
          <div class="col-md-9">
            <%= f.input_field :title, label: false, class: "form-control", placeholder: "在这里输入标题"  %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <ul class="nav nav-tabs" id="edit-tabs">
          <%= content_tag :li, link_to("编辑", '#edit_content', class: "edit-body-node edit-node", 'data-toggle': 'tab'), class: 'active' %>
          <%= content_tag :li, link_to("预览", '#preview_content', class: "eidt-body-node preview-node", 'data-toggle': 'tab') %>
        </ul>
      </div>
      <div class="form-group", id="edit-form">
        <%= f.input :content, as: :text, label: false, input_html: { rows: 15, class: "form-control"} %>
      </div>
      <div class="form-group", id="preview-form"></div>

      <div class="form-froup pull-right">
        <%= f.button :submit, "保存", class: 'btn btn-primary' %>
      </div>

    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<% provide :title, "编辑博客" %>
<%= render 'form' %>

app/views/articles/index.html.erb
<h2>文章列表</h2>
<div>
  <table class="table table-hover">
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.category.try(:name) %></td>
          <td><%= link_to article.title, article_path(article.id) %> <%= article.updated_at.to_date %></td>
          <td>阅读 <%= article.view_count%></td>
          <td>评论 0</td>
          <td>
            <%= link_to "编辑", edit_article_path(article) %>
            <%= link_to "删除", article_path(article), method: :delete, 'data-confirm': "确定要删除吗？" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<% provide :title, "写博客" %>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container-fluid">
  <input type="hidden" id="article_area" value="<%= @article.id %>" />
  <div class="text-center">
    <%= content_tag :h1, content_tag(:span, @article.title)%>
  </div>
  <div class="post-body">
    <%= simple_format(@article.content_html) %>
  </div>
  <div class="row pull-right">
    <%= link_to "编辑", edit_article_path(@article) %>
    <%= link_to "赞", "#" %>
    <%= link_to "评论", "#" %>
  </div>
  <div id="comments_list">
  </div>
</div>

<div class="container-fluid">
  <div class="col-md-10 col-lg-10">
    <%= simple_form_for([@article,@article.comments.build]) do |f| %>
      <div class="form-group">
        <ul class="nav nav-tabs" id="edit-tabs">
          <%= content_tag :li, link_to("编辑", '#edit_content', class: "edit-body-node edit-node", 'data-toggle': 'tab'), class: 'active' %>
          <%= content_tag :li, link_to("预览", '#preview_content', class: "eidt-body-node preview-node", 'data-toggle': 'tab') %>
        </ul>
      </div>

      <div class="form-group", id="edit-form">
        <%= f.input :content, as: :text, label: false, input_html: { rows: 8, class: "form-control"} %>
      </div>
      <div class="form-group", id="preview-form"></div>

      <div class="form-froup pull-right">
        <%= f.button :submit, "保存", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<%= content_for :javascripts do %>
  <script>
    var article_id = $("#article_area").val();
    var url = "/articles/" + article_id + "/comments";
    $.get(url, function(data){
      $('#comments_list').html(data);
    })

    $('.btn').click(function(){

      $.ajax({
        url: url + ".js",
        method: 'post',
        data: { content: $("#comment_content").val() },
        success: function(data) {
          $("#comment_content").val("");
          $("#edit-form").show();
          $("#preview-form").hide();
          $("#comments_list").html(data.data);
        },
        error: function(jqXHR, textStatus, errorThrown){
          alert("评论失败！请检查日志！");
        }
      });

      return false;
    })
  </script>
<% end %>

app/views/comments/index.html.erb
<div class="clearfix"></div>
<br />

<ul class="list-group">
  <% @comments.each do |comment| %>
    <li class="list-group-item">
      <label>
        <%= simple_format(comment.content_html) %>

        <%= link_to "删除", article_comment_path(comment.article, comment), method: 'delete', "data-confirm": "确认删除该评论吗？", class: "remove-address-btn inline" %>
      </label>
    </li>
  <% end %>
</ul>

app/views/resumes/edit.html.erb
<div class="container-fluid">
  <div class="offset-md-2 col-md-8">
    <%= simple_form_for @resume do |f| %>
      <div class="form-group">
        <%= f.input :title, label: false, class: "form-control", placeholder: "请输入简历名称" %>
      </div>

      <div class="form-group">
        <%= f.input :content, as: :text, label: false, input_html: { rows: 15, class: "form-control"} %>
      </div>

      <div class="form-froup pull-right">
        <%= f.button :submit, "保存", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>注册</h1>
<% unless @user.errors.empty? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.messages.values.flatten.each do |error| %>
        <li><%= error %></li>
      <% end -%>
    </ul>
  </div>
<% end -%>

<div class="col-md-6 col-md-offset-3">
  <%= form_for :user, url: users_path, method: :post, html: { class: 'form-horizontal', id: "user_form"} do |f| %>
    <div class="form-group">
      <div class="col-lg-12">邮箱 *</div>
      <div class="col-lg-12">
        <%= f.text_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-12">密码 *</div>
      <div class="col-lg-12">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-12">密码确认 *</div>  
      <div class="col-lg-12">
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-12">
        <input type="submit" name="create_user_submit" value="创建账户" class="col-xs-12 btn btn-primary"> 
      </div>
    </div>
  <% end -%>
</div>