config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users
  resources :sessions
  delete "/logout" =>  "sessions#destroy", as: :logout
  get 'about', to: 'welcome#about'
  get 'download', to: 'welcome#download_resume'

  resources :articles do
    get :search, on: :collection
    post :preview, on: :collection
    resources :comments
  end

  resources :resumes, only: [:edit, :update]

  # 用户相关信息路由跟在用户名之后
  #constraints(id: User::USERNAME_FORMAT) do
    #resources :users, path: '', as: 'users' do
      #member do
        #get :articles
        #get :comments
      #end
    #end

  #end

  # 设置
  resource :setting do
    member do
      get :profile
      get :reward
      get :password
    end
  end

  # 后台管理
  namespace :admin do
    root 'sessions#new'
    resources :sessions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  searchkick

  belongs_to :user
  belongs_to :category
  has_many :comments

end

app/models/article_tag_ship.rb
class ArticleTagShip < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article
end

app/models/personal_category.rb
class PersonalCategory < ApplicationRecord
end

app/models/resume.rb
class Resume < ApplicationRecord

  belongs_to :user

  def generate_pdf(content)
    Prawn::Document.generate("test.pdf") do
      file = "#{Prawn::DATADIR}/fonts/gkai00mp.ttf"
      font_families["Kai"] = {
        :normal => { :file => file, :font => "Kai" }
      }
      text content, :fallback_fonts => ["Times-Roman", "Kai"]
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  attr_accessor :password, :password_confirmation

  has_many :articles, dependent: :destroy
  has_many :comments
  has_one :resume

  USERNAME_FORMAT = /[a-zA-Z0-9\-\_]*/

  def username
    self.name.nil? ? self.email.split('@').first : self.name
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :auth_user, except: [:show]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all.page(params[:page] || 1).
      per_page(params[:per_page] || 10).order('id desc')
  end

  def show
    @article.view_count += 1
    @article.save!
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.view_count = 0
    @article.content_html = markdown(@article.content)
    if @article.save
      flash[:info] = "文章发布成功！"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update_attributes(article_params)
      flash[:success] = "update article successful"
      redirect_to @article
    else
      render 'deit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "删除成功"
      redirect_to articles_path
    else
      flash[:notice] = "删除失败"
      redirect_back fallback_location: articles_path
    end
  end

  def preview
    content = markdown(params[:content])
    render html: content
  end

  def search
    @articles = Article.search(params[:key], fields: [:title], page: params[:page], per_page: 10)

    render file: 'welcome/index'
  end

  private
  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :category_id, :content)
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def edit
    @resume = current_user.resume
  end

  def update
    @resume = current_user.resume
    @resume.attributes = params.require(:resume).permit(:title, :content)
    @resume.content_html = markdown(params[:resume][:content])
    if @resume.save
      redirect_to about_path
    else
      render action: :edit
    end
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_action :auth_user
  before_action :get_user

  def show
  end

  def profile
  end

  def reward
  end

  def password
  end

  def update
    case params[:edit_path]
    when "profile"
      update_profile
    when "reward"
      update_reward
    when "password"
      update_password
    else
      update_basic
    end
  end

  private
  def get_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(
      :name, :introduction, :avatar, :city, :company,:alipay, 
      :github, :homepage, :current_password, :password, :wechat,
      :password_confirmation, :signature, :edit_path)
  end

  def update_basic
    if @user.update(user_params)
      redirect_to setting_path, notice: "更新成功！"
    else
      render "show"
    end
  end

  def update_profile
    if @user.update(user_params)
      redirect_to profile_setting_path, notice: "更新成功！"
    else
      render "profile"
    end
  end

  def update_password
    if @user.valid_password?(params[:user][:current_password])
      @user.password_confirmation = params[:user][:password_confirmation]

      if @user.change_password!(params[:user][:password])
        redirect_to new_session_path, notice: "密码更新成功，请重新登录！"
      else
        render "password"
      end
    else
      @user.errors.add :current_password, "当前密码不正确"
      render "password"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user)
      .permit(:email, :password, :password_confirmation))

    if @user.save
      Resume.create!(user_id: @user.id, title: "#{@user.username}的简历", content: "内容" )
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.all.page(params[:page] || 1).
      per_page(params[:per_page] || 10).order('id desc')
  end

  def about
    @resume = User.first.resume
  end

  def download_resume
    @resume = User.first.resume
    content = @resume.content_html.nil? ? @resume.content : @resume.content_html
    kit = PDFKit.new(content, page_size: 'Letter')
    pdf = kit.to_pdf
    file_name = "李亚中的个人简历.pdf"
    send_data(pdf, filename: file_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def avatar_tag(user, width = 96)
    if user.avatar?
      avatar_url = user.avatar.url
    else
      avatar_id = Digest::MD5::hexdigest(user.email.downcase)
      avatar_url = "https://secure.gravatar.com/avatar/#{avatar_id}"
    end
    image_tag(avatar_url, alt: user.username, class: "avatar-#{width}")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/settings/_menu.html.erb
<div class="col-sm-2 col-md-offset-1">
  <div class="panel panel-default">
    <div class="panel-body">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to " 基本资料", setting_path, class: "fa fa-user-circle" %></li>
        <li><%= link_to " 详细资料", profile_setting_path, class: "fa fa-address-card" %></li>
        <li><%= link_to " 打赏", reward_setting_path, class: "fa fa-qrcode" %></li>
        <li><%= link_to " 登录密码", password_setting_path, class: "fa fa-keyboard-o" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/settings/password.html.erb
<div class="row">
  <%= render "menu" %>

  <div class="col-md-8">
    <div class="alert alert-warning">注意！更新密码以后需要重新登陆。</div>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= simple_form_for(@user, url: setting_path, html: { method: :put }) do |f| %>
          <input type="hidden" name="edit_path" value="password" />
          <%= f.input :current_password %>
          <%= f.input :password %>
          <%= f.input :password_confirmation %>
          <div class="form-actions">
            <%= f.submit "更新密码", class: "bt btn-success" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/settings/profile.html.erb
<div class="row">
  <%= render "menu" %>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= simple_form_for(@user, url: setting_path, html: { method: :put, enctype:  "multipart/form-data" }) do |f| %>
          <input type="hidden" name="edit_path" value="profile" />
          <%= f.input :city %>
          <%= f.input :company %>
          <div class="form-group">
            <%= f.label :github, class: "control-label" %>
            <div class="input-group">
              <span class="input-group-addon">https://github.com/</span>
              <%= f.text_field :github, class: "form-control", placeholder: "账号名称" %>
            </div>
          </div>

          <%= f.input :homepage, type: :url, input_html: { placeholder: "http://"} %>
          <%= f.input :alipay %>
          <%= f.input :wechat %>
          <%= f.input :signature %>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary">更新资料</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/settings/reward.html.erb
<div class="row">
  <%= render "menu" %>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
      </div>
    </div>
  </div>
</div>

app/views/settings/show.html.erb
<div class="row">
  <%= render 'menu' %>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= simple_form_for(@user, url: setting_path, html: { method: :put, enctype: "multipart/form-data"}) do |f| %>
          <div class="row">
            <div class="col-sm-9">
              <%= f.input :name, input_html: {style: 'width: 300px'} %>
              <%= f.input :email, input: {disable: true} %>
              <%= f.input :avatar %>
              <%= f.input :introduction, as: :text, input_html: { rows: 6 } %>
            </div>

            <div class="col-sm-3">
              <div class="form-group avatar-preview" style="text-align: center;">
                <%= avatar_tag(@user) %>
              </div>
            </div>
          </div>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">更新资料</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>