config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users
  resources :sessions
  delete "/logout" =>  "sessions#destroy", as: :logout
  get 'about', to: 'welcome#about'
  get 'download', to: 'welcome#download_resume'

  resources :articles do
    get :search, on: :collection
    post :preview, on: :collection
    resources :comments
  end

  resources :resumes, only: [:edit, :update]

  # 用户相关信息路由跟在用户名之后
  #constraints(id: User::USERNAME_FORMAT) do
    #resources :users, path: '', as: 'users' do
      #member do
        #get :articles
        #get :comments
      #end
    #end

  #end

  # 设置
  resource :setting do
    member do
      get :profile
      get :reward
      get :password
    end
  end

  # 后台管理
  namespace :admin do
    root 'sessions#new'
    resources :sessions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  searchkick

  belongs_to :user
  belongs_to :category
  has_many :comments

end

app/models/article_tag_ship.rb
class ArticleTagShip < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article
end

app/models/personal_category.rb
class PersonalCategory < ApplicationRecord
end

app/models/resume.rb
class Resume < ApplicationRecord

  belongs_to :user

  def generate_pdf(content)
    Prawn::Document.generate("test.pdf") do
      file = "#{Prawn::DATADIR}/fonts/gkai00mp.ttf"
      font_families["Kai"] = {
        :normal => { :file => file, :font => "Kai" }
      }
      text content, :fallback_fonts => ["Times-Roman", "Kai"]
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  attr_accessor :password, :password_confirmation

  has_many :articles, dependent: :destroy
  has_many :comments
  has_one :resume

  USERNAME_FORMAT = /[a-zA-Z0-9\-\_]*/

  def username
    self.name.nil? ? self.email.split('@').first : self.name
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def edit
    @resume = current_user.resume
  end

  def update
    @resume = current_user.resume
    @resume.attributes = params.require(:resume).permit(:title, :content)
    @resume.content_html = markdown(params[:resume][:content])
    if @resume.save
      redirect_to about_path
    else
      render action: :edit
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user)
      .permit(:email, :password, :password_confirmation))

    if @user.save
      Resume.create!(user_id: @user.id, title: "#{@user.username}的简历", content: "内容" )
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.all.page(params[:page] || 1).
      per_page(params[:per_page] || 10).order('id desc')
  end

  def about
    @resume = User.first.resume
  end

  def download_resume
    @resume = User.first.resume
    content = @resume.content_html.nil? ? @resume.content : @resume.content_html
    kit = PDFKit.new(content, page_size: 'Letter')
    pdf = kit.to_pdf
    file_name = "李亚中的个人简历.pdf"
    send_data(pdf, filename: file_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def avatar_tag(user, width = 96)
    if user.avatar?
      avatar_url = user.avatar.url
    else
      avatar_id = Digest::MD5::hexdigest(user.email.downcase)
      avatar_url = "https://secure.gravatar.com/avatar/#{avatar_id}"
    end
    image_tag(avatar_url, alt: user.username, class: "avatar-#{width}")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/layouts/_menu.html.erb
<div class="bootstrap-admin-with-small-navbar">
  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top " role="navigation">
    <div class="container">
      <div class="row">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Boot3Admin</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">首页</a></li>
            <li ><a href="#">关于我们</a></li>			  
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">下拉菜单<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="请输入内容">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">链接</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">管理员<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">设置</a></li>
                <li><a href="#">个人资料</a></li>
                <li><a href="#">账户中心</a></li>
                <li class="divider"></li>
                <li><a href="#">退出登录</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-2 bootstrap-admin-col-left">
        <ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
          <li class="active">
            <a href="admin_root_paath"><i class="glyphicon glyphicon-chevron-right"></i> 首页</a>
          </li>
          <li class="disabled">
            <a href="#"><i class="glyphicon glyphicon-chevron-right"></i> 统计图表</a><!-- stats.html -->
          </li>
          <li>
            <a href="tables.html"><i class="glyphicon glyphicon-chevron-right"></i> 工资计算</a>
          </li>
          <li>
            <a href="tables.html"><i class="glyphicon glyphicon-chevron-right"></i> 找工作</a>
          </li>
          <li>
            <a href="tables.html"><i class="glyphicon glyphicon-chevron-right"></i> 找房子</a>
          </li>
          <li>
            <a href="tables.html"><i class="glyphicon glyphicon-chevron-right"></i> 数据表格</a>
          </li>
          <li>
            <a href="#"><span class="badge pull-right">999</span> 订单</a>
          </li>
          <li>
            <a href="#"><span class="badge pull-right">888</span> 清单</a>
          </li>
          <li>
            <a href="#"><span class="badge pull-right">666</span> 客户</a>
          </li>
          <li>
        </ul>
      </div>

      <div class="col-md-10">
        <div class="row">
          <div class="alert alert-success bootstrap-admin-alert">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>成功</h4>
            这里是操作成功提示信息！
          </div>
        </div>

        <div class="row">
          <div class="navbar navbar-default bootstrap-admin-navbar-thin">
            <ol class="breadcrumb bootstrap-admin-breadcrumb">
              <li>
                <a href="#">首页</a>
              </li>
              <li>
                <a href="#">设置</a>
              </li>
              <li class="active">工具</li>
            </ol>
          </div>
        </div>

        <div class="row">
          <div class="panel panel-default bootstrap-admin-no-table-panel">
            <div class="panel-heading">
              <div class="text-muted bootstrap-admin-box-title">统计</div>
              <div class="pull-right"><span class="badge">查看更多</span></div>
            </div>
            <div class="bootstrap-admin-panel-content bootstrap-admin-no-table-panel-content collapse in">
              <div class="col-md-3">
                <div class="easyPieChart" data-percent="73" style="width: 110px; height: 110px; line-height: 110px;">73%<canvas width="110" height="110"></canvas></div>
                <div class="chart-bottom-heading"><span class="label label-info">访问量</span></div>
              </div>
              <div class="col-md-3">
                <div class="easyPieChart" data-percent="53" style="width: 110px; height: 110px; line-height: 110px;">53%<canvas width="110" height="110"></canvas></div>
                <div class="chart-bottom-heading"><span class="label label-info">页面浏览量</span></div>
              </div>
              <div class="col-md-3">
                <div class="easyPieChart" data-percent="83" style="width: 110px; height: 110px; line-height: 110px;">83%<canvas width="110" height="110"></canvas></div>
                <div class="chart-bottom-heading"><span class="label label-info">用户</span></div>
              </div>
              <div class="col-md-3">
                <div class="easyPieChart" data-percent="13" style="width: 110px; height: 110px; line-height: 110px;">13%<canvas width="110" height="110"></canvas></div>
                <div class="chart-bottom-heading"><span class="label label-info">订单</span></div>
              </div>
            </div>
          </div>
        </div>

        <div class="row bootstrap-admin-no-edges-padding">
          <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <div class="text-muted bootstrap-admin-box-title">用户</div>
                <div class="pull-right"><span class="badge">1,234</span></div>
              </div>
              <div class="bootstrap-admin-panel-content">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>First Name</th>
                      <th>Last Name</th>
                      <th>Username</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>Mark</td>
                      <td>Otto</td>
                      <td>@mdo</td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>Jacob</td>
                      <td>Thornton</td>
                      <td>@fat</td>
                    </tr>
                    <tr>
                      <td>3</td>
                      <td>Vincent</td>
                      <td>Gabriel</td>
                      <td>@gabrielva</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <div class="text-muted bootstrap-admin-box-title">订单</div>
                <div class="pull-right"><span class="badge">752</span></div>
              </div>
              <div class="bootstrap-admin-panel-content">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Product</th>
                      <th>Date</th>
                      <th>Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>Coat</td>
                      <td>02/02/2013</td>
                      <td>$25.12</td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>Jacket</td>
                      <td>01/02/2013</td>
                      <td>$335.00</td>
                    </tr>
                    <tr>
                      <td>3</td>
                      <td>Shoes</td>
                      <td>01/02/2013</td>
                      <td>$29.99</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>个人网站管理平台</title>
    <!--移动端支持meta-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= render 'admin/layouts/menu' %>
    <div class="container">
      <% unless flash[:notice].blank? %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end %>
      <br/>
      <br/>
      <%= yield %>
      <br/>
      <br/>
    </div>
    <div class="container">
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <%= javascript_include_tag 'admin' %>
    <%= yield :javascripts %>
  </body>
</html>

app/views/admin/layouts/menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= admin_root_path %>">管理平台</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= admin_root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">分类</a></li>
        <li><a href="#">商品</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "退出", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2018 LYZ的个人网站
    <br>Design by
    <a href="http://blog.csdn.net/luoyegufei129" target=_new>Asia Lee</a>
    </p>
</footer>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">个人网站</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home <span class="sr-only">(current)</span></a></li>
      </ul>
      <%= form_tag search_articles_path, method: :get, class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <input type="text" name="key" value="<%= params[:key] %>" class="form-control" placeholder="文章搜索..">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "关于", about_path %></li>
        <li><%= link_to "文章", articles_path %></li>
        <% unless logged_in? %>
          <li><a href="<%= new_user_path %>">注册</a></li>
          <li><a href="<%= new_session_path %>">登录</a></li>
          <li><a href="<%= download_path %>">简历下载</a></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= avatar_tag(current_user, 24) %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= user_path(current_user) %>"><%= current_user.username %></a></li>
              <li role="separator" class="divider"></li>
              <li><a href="<%= setting_path %>">个人资料设置</a></li>
              <li><a href="<%= edit_resume_path(current_user.resume) %>">编辑个人简历</a></li>
              <li><a href="<%= download_path %>">导出PDF格式的简历</a></li>
              <li><%= link_to "写文章", new_article_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "退出", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>李书瑶的个人网站</title>
    <!--移动端支持meta-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <div class="container">
      <% unless flash[:notice].blank? %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end %>
      <br/>
      <br/>
      <%= yield %>
      <br/>
      <br/>
    </div>
    <div class="container">
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :javascripts %>
  </body>
</html>